config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/home'
  get 'pages/about_us'
  get 'pages/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def about_us; end

  def contact; end

  def name; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PandaGinClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="min-h-screen flex flex-col bg-gray-30">
    <%= render 'shared/navbar' %>
    <%= yield %>
    <div class="mt-auto">
      <p>Footer</p>
    </div>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1>Pages#about_us</h1>
<p>Find me in app/views/pages/about_us.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<p>Test</p>

app/views/shared/_navbar.html.erb
<nav 
  data-controller="dropdown"
  class="mt-16 fixed top-0 w-full"
>
  <div 
    class="flex justify-between items-center"
  >
    <div
      style="max-width: 40px;"  
    >
      <i 
        class="fa fa-bars p-2 ml-4 cursor-pointer"
        style="font-size: 40px;"
        data-action="click->dropdown#toggle"
        data-dropdown-target="dropdownButton"
        ></i>
    </div>
    <div class="flex flex-col items-center">
      <%= link_to "Panda", root_path, class: "text-3xl" %>
      <h2 class="text-xs">Organic gin</h2>
    </div>
    <div class="mr-4">
      <i class="fa fa-user fa-lg p-2"></i>
      <i class="fa fa-shopping-bag fa-lg p-2"></i>
    </div>
  </div>
  <%# Dropdown menu %>
  <ul
    class="flex flex-col items-center h-screen"
  >
    <li>
      <%= link_to "About us", pages_about_us_path %>
    </li>
    <li>
      <%= link_to "Contact", pages_contact_path %>
    </li>
  </ul>
</nav>